# Generated by Django 3.1.6 on 2021-03-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fb_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='insta_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='web_url',
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
