# Generated by Django 3.1.6 on 2021-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210314_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
